##SQL-Connection

SQL_USER: "root"
SQL_PASSWORD: ""
SQL_DATABASE: "staff"
SQL_HOST: "staff"

##Prefixe
BanPrefix: "&8┃ &4Punish &8× "
StaffPrefix: "&8┃ &eStaff &8× "
NotifyPrefix: "&8┃ &3Notify &8× "
ReportPrefix: "&8┃ &cReport &8× "
VotePrefix: "&8┃ &bVote &8× "
PremiumPrefix: "&8┃ &6Premium &8× "
HeadPrefix: "&8┃ &3Head &8× "
ShopPrefix: "&8┃ &2Shop &8× "


##Messages
NoPermission: "&4You don´t have the permissions fot this command!"
LoginFirst: "&cYou must be logged in to use this command!"
CreateAccountFirst: "&cYou need to create an account before you can use this command!"
InternalError: "&cThere was an internal error! Please contact an admin!"
AutomatticlyExtended: "&aThe punish has been automatically due to the players &aban history."
BanNotify: "&8&l=====================================\n\n&8┃ &3Notify&8 × &aThe Player &e%player% &ahas been banned by &3%punisher% &afor &athe ID: &c%id%&7 | &aBanID: &c%banid%.\n\n&8&l====================================="
ReportNotify: "&8&l=====================================\n\n&8┃ &3Notify&8 × &aThe Player &e%player% &ahas been reported by &3%punisher% &afor &athe Reason: &c%id%&7 | &aReportID: &c%banid%.\n\n&8&l====================================="
Reloaded: "&aYou successfully reloaded the configs!"
InvalidNumber: "&cPlease use a number to search a BanID!"
PunishAlreadyInactive: "&cThe punishment you´re looking for is already inactive!"
SetBanIDToInactive: "&aYou successfully set the BanID to inactive!"
BanDoesNotExist: "&cThe ban you´re looking for does not exist!"
InvalidTime: "&cThe time format you used is invalid. Please use: s/min/d/m/p"
RefreshedEndtime: "&aYou successfully refreshed the end time of the &apunishment."
IDFormat: "&c%id% &8| &4%reason% &8| &e%time% &8| &3%type%"
WrongPassword: "&cThe password you entered is wrong."
Login: "&aYou successfully &clogged &ain!"
Logout: "&aYou successfully &clogged &aout!"
CreatedAccount: "&aYou successfully created an account!"
PasswordDontMatch: "&cThe passwords you entered do not match!"
AlreadyAccount: "&cYou already have an account!"
NewPasswordCantBeOld: "&cThe new password can´t be the old!"
UpdatedPassword: "&aYou successfully updated your password!"
InvalidID: "&cPlease use a valid ID!"
IDAlreadyExists: "&cThe uses ID does already exist!"
InvalidTYPE: "&cPlease use a valid punish type. BAN/MUTE"
SavedID: "&aYou successfully saved the ID to the ids.yml!"
JoinedTC: "&aYou successfully &cjoined &athe team chat!"
LeftTC: "&aYou successfully &cleft &athe team chat!"
InvalidPlayer: "&cThe player you are looking for was never on the network before!"
PlayerAlreadyBanned: "&cThe player is already banned!"
BanScreen: "§8┃ §4Punish §8× §7You have been banned!\n
             \n
             §7Reason » §e%reason%\n
             §7BanID » §4%banid%\n
             §7Banned by » §c%punisher%\n
             §7Until: §a%unbanned%\n
             \n
             §8┃ §4Punish §8× §7You have been banned!"
TeamChatFormat: "&8┃ &3Notify&8 × &7%name% &b%server% §r§8➟§r %message%"
MuteMessage: "&cYou have been muted.&7 Until » §e%date% §7| Reason » §e%reason% §7| §7BanID » §4%banid% §7| §7Muted by » §c%punisher%"
Ubannable: "&cThe player you´re trying to punish is not ban-able."
NoBansYet: "&cThe player does´nt have any bans yet!"
NoBansAtAll: "&cThe players does´nt have any bans at all!"
ClearedHistory: "&aYou successfully cleared the history!"
BanRemoved: "&aThe ban has been removed and deleted from the database"
SameGroup: "&cYou can´t punish players who are in the team."
ReportCreated: "&aThe report was successfully created. You will be notified, when your report was looked by a moderator."
PlayerOffline: "&cThe reported player went offline, you have to wait until he is online to edit the report, or delete it."
AlreadyEdited: "§cThis report is already being edited."
YouAreNotEditing: "§cYou are not editing a report at the moment."
ReportFinished: "§aThe report was successfully closed."
DidNotWriteAnyMessage: "§cThe player did not write any messages yet."
NowEditing: "§aYou are now editing the report %id%"
AlreadyEditing: "§cYou can only edit one report at once."
ReportDoesNotExist: "§cThe id you are looking for does not exist."
ReportIsNowBeeingEditied: "§aYour report will now be processed by a moderator..."
AlreadyReported: "§cYou already reported the player for the given reason."
CantReportYourself: "§cYou can´t report yourself."
ReportDeleted: "&aYou successfully deleted the report:&c %id%"
AlreadyVoting: "&cThere is already a voteprocess."
AlreadyHasVote: "&cYou already voted in the last week. Please wait at least 7 days between every vote"
AlreadyVoted: "&cYou already voted, you can only vote once per vote."
Voted: "&aYou successfully voted for %vote%"
CantVoteForYourSelf: "&cYou can´t vote for yourself."
CantVoteATM: "&cYou can´t vote at the moment."
CantVoteATeamMember: "&cYou cant vote for a teammember."
AlreadyHasGroup: "&cThe player already has a group."
NeedToWait: "&cYou need to wait 7 Days before giving another player premium."
SetPremium: "&aYou successfully gave the player %player% premium for one week."
AlreadyGaveHeadAgent: "&cYou already gave yourself a head. Please wait at least 4 Weeks before getting another one."
AlreadyGaveHeadZiemlich: "&cYou already gave yourself a head. Please wait at least 2 Weeks before getting another one."
GaveSkull: "&aYou successfully gained the skull from %player%"
GotPremium: "&aThe player %player% gave you premium for a week."
CantOpenInGamemode: "&cYou can´t open the shop in gamemode."
AlreadyHaveItem: "&cYou already bought that item."
BoughtItem: "&aYou successfully bought that item."
NotEnoughMoney: "&cYou do not have enough money for that item."
NeedItemToSell: "&cYou need to have the item in your inventory to sell it."